### ISSUE TITLE
您好，项目很符合需求，但是有个小问题

### ISSUE THREAD

**Issue by aaq1adqwe** [fengxxc/wechatmp2markdown#1]
能否添加保存图片功能，或者自动转成base64插入到md中

没有图片保存下来的文章，也是不完整的。

**Comment by fengxxc** [comment]
> 能否添加保存图片功能，或者自动转成base64插入到md中
> 
> 没有图片保存下来的文章，也是不完整的。

目前有图片自动转成base64插入到md的功能的；
保存图片的功能我后续会开发的^_^.

**Comment by fengxxc** [comment]
#[v1.1.0版，](https://github.com/fengxxc/wechatmp2markdown/releases/tag/v1.1.0)
已经支持保存图片功能，请添加命令参数 `--image=save` ，详见README。
