### ISSUE TITLE
我哪里写错了吗

### ISSUE THREAD

**Issue by hyhse** [fengxxc/wechatmp2markdown#11]
PS C:\Windows\system32> & "C:\Users\test\OneDrive\0_source\wechatmp2markdown-master\wechatmp2markdown_win64.exe" "https://mp.weixin.qq.com/s/VaLyn1gCYQxQMpjZaHjWRg" "D:\APPDATA\shuke" --image=save
url: https://mp.weixin.qq.com/s/VaLyn1gCYQxQMpjZaHjWRg, filename: D:\APPDATA\shuke

![image](https://github.com/user-attachments/assets/6e9adfcb-5424-4039-ad57-001b1a502192)

**Comment by fengxxc** [comment]
你没有写错命令。
https://mp.weixin.qq.com/s/VaLyn1gCYQxQMpjZaHjWRg 这个文章的排版太独特了，他的结构跟我所了解的公众号文章完全不一样，目前的程序无法解析它。

**Comment by hyhse** [comment]
谢谢

**Comment by hyhse** [comment]
谢谢
