### ISSUE TITLE
win10 下title有：时，出错

### ISSUE THREAD

**Issue by saichen12** [fengxxc/wechatmp2markdown#12]
https://mp.weixin.qq.com/s/FTB1rCRNoBXKHFJWrUqxUg
https://mp.weixin.qq.com/s/z1nX-aC42qgA8peeqBBFGw

**Comment by fengxxc** [comment]
v1.1.8 已修复
https://github.com/fengxxc/wechatmp2markdown/releases/tag/v1.1.8

**Comment by saichen12** [comment]
谢谢
