### ISSUE TITLE
当微信文章名含有不可用于创建文件夹或文件名 的字符时

### ISSUE THREAD

**Issue by MrMu666** [fengxxc/wechatmp2markdown#2]
当微信文章名含有不可用于创建文件夹或文件名 的字符时，程序无法正确处理。
如：https://mp.weixin.qq.com/s/FAveSRMt_-ZcuWNYmmys1w

在Windows操作系统中，文件名需要遵守以下命名规则： 文件名不包含以下任何字符：“（双引号）、*（星号）、<（小于）、>（大于）、？（问号）、\（反斜杠）、/（正斜杠）、|（竖线）、：（冒号）。 文件名不要以空格、句号、连字符或下划线开头或结尾。

**Comment by fengxxc** [comment]
通过你提供的微信文章链接，我发现程序还存在其他问题，包括：
- 列表项段落换行
- 不支持表格的解析

这些稍后会解决_(:з)∠)_

**Comment by triangle959** [comment]
我在v1.1.11测试时发现：如果文章标题有/的话，会被分成子文件夹，导致最后md文件没有写入
例如：
https://mp.weixin.qq.com/s/D1ZipivoPCJpnMMfTlwo5A

**Comment by fengxxc** [comment]
> 我在v1.1.11测试时发现：如果文章标题有/的话，会被分成子文件夹，导致最后md文件没有写入 例如： https://mp.weixin.qq.com/s/D1ZipivoPCJpnMMfTlwo5A

你使用的是什么系统？
我在 Windows 和 Linux 测是没有问题的。
