### ISSUE TITLE
Linux 版本执行后提示权限不足

### ISSUE THREAD

**Issue by zlgxzswjy** [fengxxc/wechatmp2markdown#5]
【复现流程】
确认当前目录是由写入权限的， 并且由程序自己创建的目录也是有写权限的
linux命令执行：
```bash
./wechatmp2markdown-v1.1.5_linux_amd64 https://mp.weixin.qq.com/s/UCXzpKVjPss5vLvu-GXGOw ./ --image=save
```
![image](https://github.com/fengxxc/wechatmp2markdown/assets/12388719/4463d07f-44c4-4edf-98eb-18939243b924)

```bash
./wechatmp2markdown-v1.1.5_linux_amd64 https://mp.weixin.qq.com/s/UCXzpKVjPss5vLvu-GXGOw ./ --image=url

```
![image](https://github.com/fengxxc/wechatmp2markdown/assets/12388719/29cac7b4-fb19-4bf2-9111-a9c04b235d75)

但是执行后都提示无法写入，权限不足

**Comment by zlgxzswjy** [comment]
Windows可以完美运行

**Comment by fengxxc** [comment]
很抱歉这么晚才回复。
该问题在v1.1.6已修复: 
https://github.com/fengxxc/wechatmp2markdown/releases/tag/v1.1.6
